pull_request_rules:
- actions:
    label:
      add:
      - unstable
      - foobar
      remove:
      - stable
      - what
  conditions:
  - base=20210323070708/test_label/master
  - label=stable
  name: rename label
