pull_request_rules:
- actions:
    merge:
      method: merge
      rebase_fallback: null
  conditions:
  - base=20210519152819/test_backport_with_title_and_body/master
  - label=backport-#3.1
  name: Merge on master
- actions:
    backport:
      body: 'foo: {{destination_branch}}'
      branches:
      - 20210519152819/test_backport_with_title_and_body/stable/#3.1
      title: 'foo: {{destination_branch}}'
  conditions:
  - base=20210519152819/test_backport_with_title_and_body/master
  - label=backport-#3.1
  name: Backport to stable/#3.1
