pull_request_rules:
- actions:
    merge:
      method: merge
      rebase_fallback: null
  conditions:
  - base=20210415093905/test_backport_with_title/master
  - label=backport-#3.1
  name: Merge on master
- actions:
    backport:
      branches:
      - 20210415093905/test_backport_with_title/stable/#3.1
      title: 'foo: {{branch}}'
  conditions:
  - base=20210415093905/test_backport_with_title/master
  - label=backport-#3.1
  name: Backport to stable/#3.1
