pull_request_rules:
- actions:
    merge:
      method: rebase
  conditions:
  - base=20210415174842/test_short_teams/master
  - status-success=continuous-integration/fake-ci
  - approved-reviews-by=@testing
  name: Merge on master
