pull_request_rules:
- actions:
    merge:
      strict: smart
  conditions:
  - base=20210519150849/test_merge_failure_smart_strict/master
  - status-success=continuous-integration/fake-ci
  name: strict merge on master
