pull_request_rules:
- actions:
    merge:
      method: merge
      rebase_fallback: null
  conditions:
  - base=20210409180802/test_backport_with_title/master
  - label=backport-#3.1
  name: Merge on master
- actions:
    backport:
      branches:
      - 20210409180802/test_backport_with_title/stable/#3.1
      title: 'backport of pull #{{number}}'
  conditions:
  - base=20210409180802/test_backport_with_title/master
  - label=backport-#3.1
  name: Backport to stable/#3.1
