pull_request_rules:
- actions:
    comment:
      message: '@mergifyio copy 20210408162211/test_command_copy/stable/#3.1 20210408162211/test_command_copy/feature/one'
  conditions:
  - base=20210408162211/test_command_copy/master
  name: auto-copy
