defaults:
  actions:
    backport:
      branches:
      - stable/#3.1
      - feature/one
pull_request_rules:
- actions:
    comment:
      message: '@mergifyio backport'
  conditions:
  - base=20210407194646/test_command_backport_with_defaults/master
  name: auto-backport
