pull_request_rules:
- actions:
    merge: {}
  conditions:
  - base!=20210519121412/test_change_mergify_yml/master
  name: nothing
- actions:
    merge: {}
  conditions:
  - label!=wip
  name: foobar
