pull_request_rules:
- actions:
    dismiss_reviews:
      approved: true
      changes_requested:
      - mergify-test1
  conditions:
  - base=20210323000447/test_dismiss_reviews/master
  name: dismiss reviews
