pull_request_rules:
- actions:
    merge:
      method: squash
  conditions:
  - base=20210707194120/test_merge_custom_msg_rn/master
  - status-success=continuous-integration/fake-ci
  name: Merge on master
