pull_request_rules:
- actions:
    comment:
      message: WTF?
  conditions:
  - base=20210707193447/test_debugger/master
  - or:
    - label=doubt
    - label=suspect
  - and:
    - number>0
    - title~=pull request
  name: comment
