defaults:
  actions:
    backport:
      branches:
      - 20210407210610/test_command_backport_with_defaults/stable/#3.1
      - 20210407210610/test_command_backport_with_defaults/feature/one
pull_request_rules:
- actions:
    comment:
      message: '@mergifyio backport'
  conditions:
  - base=20210407210610/test_command_backport_with_defaults/master
  name: auto-backport
