pull_request_rules:
- actions:
    merge:
      method: rebase
  conditions:
  - base=20210415181138/test_teams/master
  - status-success=continuous-integration/fake-ci
  - approved-reviews-by=@mergifyio-testing/testing
  name: valid teams
- actions:
    merge:
      method: rebase
  conditions:
  - base=20210415181138/test_teams/master
  - status-success=continuous-integration/fake-ci
  - approved-reviews-by=@testing
  name: short teams
- actions:
    merge:
      method: rebase
  conditions:
  - base=20210415181138/test_teams/master
  - status-success=continuous-integration/fake-ci
  - approved-reviews-by=@mergifyio-testing/testing/azerty
  name: invalid-format
- actions:
    merge:
      method: rebase
  conditions:
  - base=20210415181138/test_teams/master
  - status-success=continuous-integration/fake-ci
  - approved-reviews-by=@mergifyio-testing/noexists
  name: not exists teams
- actions:
    merge:
      method: rebase
  conditions:
  - base=20210415181138/test_teams/master
  - status-success=continuous-integration/fake-ci
  - approved-reviews-by=@another-org/testing
  name: invalid organization
