pull_request_rules:
- actions:
    delete_head_branch:
      force: true
  conditions:
  - base=20210712170242/test_delete_branch_with_dep_force/master
  - label=merge
  - merged
  name: delete on merge
