pull_request_rules:
- actions:
    merge:
      method: merge
  conditions:
  - base=20210519124701/test_merge_invalid_custom_msg/master
  - status-success=continuous-integration/fake-ci
  name: merge
