pull_request_rules:
- actions:
    merge:
      method: merge
      rebase_fallback: null
  conditions:
  - base=20210402095758/test_backport_with_labels/master
  - label=backport-#3.1
  name: Merge on master
- actions:
    backport:
      branches:
      - 20210402095758/test_backport_with_labels/stable
      labels:
      - backported
  conditions:
  - base=20210402095758/test_backport_with_labels/master
  - label=backport-#3.1
  name: Backport to stable/#3.1
