pull_request_rules:
- actions:
    queue:
      name: default
      priority: high
  conditions:
  - base=20210715080430/test_queue_already_ready/master
  - label=queue
  name: Merge priority high
queue_rules:
- conditions:
  - labe=queue
  name: default
  speculative_checks: 5
