pull_request_rules:
- actions:
    comment:
      message: '@mergifyio copy 20210630132902/test_command_copy/stable/#3.1 20210630132902/test_command_copy/feature/one'
  conditions:
  - base=20210630132902/test_command_copy/master
  name: auto-copy
