pull_request_rules:
- actions:
    comment:
      message: review-requested user
  conditions:
  - base=20210323124455/test_requested_reviews/master
  - review-requested=sileht
  name: user
- actions:
    comment:
      message: review-requested team
  conditions:
  - base=20210323124455/test_requested_reviews/master
  - review-requested=@testing
  name: team
