pull_request_rules:
- actions:
    comment:
      message: '@mergifyio backport 20210630132541/test_command_backport/stable/#3.1
        20210630132541/test_command_backport/feature/one'
  conditions:
  - base=20210630132541/test_command_backport/master
  name: auto-backport
