pull_request_rules:
- actions:
    review:
      type: APPROVE
  conditions:
  - base=20210707210432/test_review/master
  name: approve
- actions:
    review:
      message: WTF?
      type: REQUEST_CHANGES
  conditions:
  - base=20210707210432/test_review/master
  - '#approved-reviews-by>=1'
  name: requested
