pull_request_rules:
- actions:
    comment:
      message: and or pr
  conditions:
  - or:
    - and:
      - base=20210615131614/test_and_or/master
      - closed
      - label=foo
    - merged
  name: no-draft
