pull_request_rules:
- actions:
    merge:
      method: merge
  conditions:
  - base=20210519103320/test_merge_custom_msg_merge/master
  - status-success=continuous-integration/fake-ci
  name: Merge on master
