pull_request_rules:
- actions:
    close: {}
  conditions:
  - base=20210609142003/test_disabled/master
  - -closed
  - label!=foo
  disabled:
    reason: code freeze
  name: merge
- actions: {}
  conditions:
  - base=20210609142003/test_disabled/master
  - closed
  - label=foo
  name: nothing
