pull_request_rules:
- actions:
    merge:
      strict: true
  conditions:
  - base=20210707194652/test_merge_strict_default/master
  - status-success=continuous-integration/fake-ci
  - '#approved-reviews-by>=1'
  name: smart strict merge on master
