pull_request_rules:
- actions:
    comment:
      message: review-requested user
  conditions:
  - base=20210630121450/test_requested_reviews/master
  - review-requested=mergify-test3
  name: user
- actions:
    comment:
      message: review-requested team
  conditions:
  - base=20210630121450/test_requested_reviews/master
  - review-requested=@testing
  name: team
