pull_request_rules:
- actions:
    merge:
      method: rebase
  conditions:
  - base=20210515110747/test_rebase/master
  - status-success=continuous-integration/fake-ci
  - '#approved-reviews-by>=1'
  name: Merge on master
