pull_request_rules:
- actions:
    merge:
      method: merge
  conditions:
  - base=20210519124015/test_merge_and_closes_issues/master
  - status-success=continuous-integration/fake-ci
  name: Merge on master
