pull_request_rules:
- actions:
    merge:
      method: merge
      rebase_fallback: null
  conditions:
  - base=20210407090754/test_backport_merge_commit_regexes/master
  - label=backport-#3.1
  name: Merge on master
- actions:
    backport:
      assignees:
      - '{{ assignees }}'
      regexes:
      - ^20210407090754/test_backport_merge_commit_regexes/stable/.*$
  conditions:
  - base=20210407090754/test_backport_merge_commit_regexes/master
  - label=backport-#3.1
  name: Backport to stable/#3.1
